name: Deploy to Production

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Specify your Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Production Branch
      run: |
        git config --global user.name 'Automated Production Deployment'
        git checkout --orphan temporary
        git add -f dist/
        git commit -m "Deploy production version"
        git mv dist/* .
        git clean -fdx
        git branch -M deployed
        git push -f origin deployed