# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Google
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: Gemini 2.0 Flash
    provider: google
    model: gemini-2.0-flash-exp
    apiKey: AIzaSyCZRNR9F72G2aGx467oiTTetT6ipiR_7f8

