name: Compress and Push to Builded Functions Branch

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  compress_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify Folder Exists
        run: |
          if [ ! -d "functions/share" ]; then
            echo "Directory functions/share does not exist!"
            exit 1
          fi

      - name: Compress Share Folder Contents
        run: |
          tar -czf share.tar.gz -C functions/share .
          if [ ! -f "share.tar.gz" ]; then
            echo "share.tar.gz was not created!"
            exit 1
          fi

      - name: Checkout builded_functions Branch
        uses: actions/checkout@v3
        with:
          ref: builded_functions
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for Existing Archive and Remove If Found
        run: |
          if [ -f "share.tar.gz" ]; then
            echo "share.tar.gz found. Removing it."
            git rm share.tar.gz
          else
            echo "share.tar.gz not found. Skipping deletion."
          fi

      - name: Copy Archive and Commit
        run: |
          cp ../share.tar.gz .
          git add share.tar.gz
          git commit -m "Add compressed share folder contents archive"

      - name: Push Changes
        run: git push origin builded_functions --force
