name: Compress and Push to Builded Functions Branch

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  compress_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify Folder Exists
        run: |
          if [ ! -d "functions/share" ]; then
            echo "Directory functions/share does not exist!"
            exit 1
          fi

      - name: Compress Share Folder Contents to /tmp
        run: |
          tar -czf /tmp/share.tar.gz -C functions/share .  # Use -C to change directory, removing ./

      - name: Checkout builded_functions Branch
        uses: actions/checkout@v3
        with:
          ref: builded_functions
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git User
        run: |
          git config user.name "Your GitHub Username"
          git config user.email "your-email@example.com"

      - name: Check for Existing Archive and Remove If Found
        run: |
          if [ -f "share.tar.gz" ]; then
            echo "share.tar.gz found in the repository. Removing it."
            git rm share.tar.gz
          else
            echo "No existing share.tar.gz found. Skipping removal."
          fi

      - name: Copy Archive from /tmp and Commit
        run: |
          cp /tmp/share.tar.gz .
          git add share.tar.gz
          git commit -m "Add compressed share folder contents archive"

      - name: Push Changes
        run: git push origin builded_functions --force
