name: Deploy

on:
  workflow_run:
    workflows: ["Deploy SPA to builded branch"]  # Replace "Build" with the exact name of your build workflow
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Pull Latest Code
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}  # Custom SSH port
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/karpad/tsada 
            git fetch origin
            git reset --hard origin/builded