name: Deploy SPA to builded branch

on:
  push:
    branches:
      - main  # or your main development branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the version of Node.js that your project requires

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Adjust this if your build command is different

      - name: Get version from package.json
        id: get_version
        run: echo "::set-output name=VERSION::$(node -p -e "require('./package.json').version")"

      - name: Deploy to builded branch
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git clone --branch=builded --single-branch https://github.com/${{ github.repository }} deploy
          cd deploy
          rm -rf *  # Remove all existing files in the builded branch
          cp -r ../dist/* .  # Copy the built files to the builded branch
          git add .
          git commit -m "Deploy version ${VERSION}-r to builded branch"
          git push origin builded
