name: Retrieve Artifact and Push to Builded Functions Branch

on:
  repository_dispatch:
    types: [retrieve_artifact]

jobs:
  retrieve_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: share-archive
          path: /tmp

      - name: Verify Artifact Download
        run: ls -la /tmp/share.tar.gz

      - name: Checkout builded_functions Branch
        uses: actions/checkout@v3
        with:
          ref: builded_functions
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clear Existing Files
        run: |
          git rm -rf .
          git clean -fxd

      - name: Copy Artifact and Commit
        run: |
          cp /tmp/share.tar.gz .
          git add share.tar.gz
          git commit -m "Add compressed share folder contents archive"

      - name: Push Changes
        run: git push origin builded_functions --force
