name: Compress and Push to Builded Functions Branch

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  compress_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Verify Folder Exists
        run: |
          if [ ! -d "functions/share" ]; then
            echo "Directory functions/share does not exist!"
            exit 1
          fi

      - name: List Contents of functions/share
        run: ls -la functions/share

      - name: Compress Share Folder Contents
        run: |
          tar -czf share.tar.gz -C functions/share .  # Compress contents of the share folder directly
          if [ ! -f "share.tar.gz" ]; then
            echo "share.tar.gz was not created!"
            exit 1
          fi

      - name: Copy Archive to Temporary Location
        run: |
          mkdir temp_archive
          cp share.tar.gz temp_archive/

      - name: Switch to builded_functions branch
        run: |
          git config --global user.name "Your GitHub Username"
          git config --global user.email "your-email@example.com"
          git checkout -B builded_functions

      - name: Remove existing files in builded_functions branch
        run: |
          git rm -rf .
          git clean -fxd

      - name: Move and Commit Archive from Temporary Location
        run: |
          cp temp_archive/share.tar.gz .
          git add share.tar.gz
          git commit -m "Add compressed share folder contents archive"

      - name: Push changes
        run: git push origin builded_functions --force
