name: Compress and Push to Builded Functions Branch

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  compress_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compress Share Folder Contents
        run: |
          tar -czf share.tar.gz -C functions/share .  # Compress contents of the share folder directly

      - name: Switch to builded_functions branch
        run: |
          git config --global user.name "Your GitHub Username"
          git config --global user.email "your-email@example.com"
          git checkout -B builded_functions

      - name: Remove existing files in builded_functions branch
        run: |
          git rm -rf .
          git clean -fxd

      - name: Move archive to branch and commit
        run: |
          mv share.tar.gz .
          git add share.tar.gz
          git commit -m "Add compressed share folder contents archive"

      - name: Push changes
        run: git push origin builded_functions --force
